spring:
  flyway:
    out-of-order: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/vetDb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json