version: '3.7'
services:
  postgres-processway:
    container_name: vetDb
    ports: [ '127.0.0.1:5432:5432' ]
    image: 'postgres:15'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'vetDb'
      PGDATA: '/var/lib/postgresql/data/pgdata'
